Add the base classes used to build finite state machines
black-omen/traders pull request #1
Opened 2017-07-19 19:40 UTC by sdeslauriers

This commit adds the `State`, `Transition`, and `FiniteStateMachine` classes which will be used to build traders. Testing is still minimal and will have to be improved.

2017-07-25 16:07 UTC, gagdiez commented on traders/fsm.py
> +
remove white space

2017-07-25 16:12 UTC, gagdiez commented on traders/fsm.py
> +    def pretty_print(self):
if it's only for debugging then we should call it _pretty_print, otherwise this can be the string representation

2017-07-25 16:24 UTC, gagdiez commented on traders/fsm.py
> +        matches = (t for t in self._transitions if t.match(state, event))
Since now we have the name of the states, I think we should create a dictionary(str, str) -> Transition using the name of the state and the event.

2017-07-25 16:26 UTC, gagdiez commented on tests/test_fsm.py
> +    def test_counting_fsm(self):
Nice!!!!!! :)

2017-07-25 16:26 UTC, gagdiez requested changes
I marked two minor things in the code.

Comment: I think we should add the following properties in the FSM: "current_state" and "final states = list(states)". This will allows us to easily check if a FSM ended up correctly (at least in a correct state) before using it somewhere else. Besides, we don't have a simple way to check in which state is the FSM right now.

2017-07-26 18:02 UTC, sdeslauriers commented on traders/fsm.py
> +
I did it, but I don't think this is PEP8.

2017-07-26 18:05 UTC, sdeslauriers commented on traders/fsm.py
> +        matches = (t for t in self._transitions if t.match(state, event))
I see no justification for this. Different implementation with no significant advantages/disadvantages.

2017-07-26 18:16 UTC, sdeslauriers commented
I don't this we should add `current_state` and `final_states` as attributes. They would never be referenced anywhere in the code. They can temporarily be added when debugging if we notice problems.

2017-07-26 21:48 UTC, gagdiez approved these changes

2017-07-26 21:48 UTC, merged